name: PR-CI

on:   
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/src
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
